### ISSUE TITLE
Reference count missing for classes in /.../ namespace

### ISSUE THREAD

**Issue by fabianlupa** [andau/abap-code-insight#4]
I think the pattern here:
https://github.com/andau/abap-code-insight/blob/698add3ceca96777d488026fc38c45a6a046d11c/adt.codemining/src/abap/codemining/element/extractor/ClassHeaderElementExtractor.java#L12-L13
does not take into account reservered namespaces, like /ABC/.
For theses classes the info line does not show up.

![image](https://user-images.githubusercontent.com/5270359/51835269-32735400-22fd-11e9-8c3d-9809411c1e45.png)

I also noticed the reference count for `CLASS ... DEFINITION LOAD.`, not sure if that is intended?

**Comment by andau** [comment]
Thats right, thanks for pointing out. I changed it but did not yet included it in the latest version as it is untested. 
Nevertheless I will take an view on the outline functionality maybe I get there a more safer element info than with parsing it by regex

**Comment by fabianlupa** [comment]
24a58b720bfcf3f3e5d8d4dbd7722755846027d2 has fixed it. Thanks!
