### ISSUE TITLE
eclipse shutdown with rename wizard

### ISSUE THREAD

**Issue by swixfort** [andau/abap-code-insight#5]
Hi, I noticed that eclipse has issues with the rename wizard after installing abap code insight.
It stays in this phase:
![image](https://user-images.githubusercontent.com/8238288/51845427-d0741800-2317-11e9-8748-4817b6fc49bc.png)
Maybe there's some infinite loop while renaming and trying to get the reference?

After terminating eclipse with the task manager and reopening it, the variable was renamed successfully.

**Comment by andau** [comment]
Hi. How many abap classes have been affected of the renaming. 
I could not reproduce it as I am already working with a newer version. 
Maybe you could update to the newest version 0.2.1.1 (and performing an eclipse.exe -clean from the command line if the plugin is not activated after the update) and tell me if the freezing behaviour still happens.

**Comment by swixfort** [comment]
The renaming took place in just one method of a class. Tomorrow I will check the new version and the -clean thingy.

**Comment by swixfort** [comment]
Update: I tried several things:
1. updating to 0.2.1.1
2. starting with -clean
3. removing everything else but code insight
4. removing project and adding them back

Everything results in still freezing with the renaming wizard. The step which is freezing is the last one. I can step through giving a new name and previewing source changes, when I hit Finish, the wizard dies. Even removing the workspace didn't help.

After uninstalling code inside everything worked well.

**Comment by andau** [comment]
Unfortunetly I could not yet reproduce this issue. Maybe you could activate in the ABAP Communication log the logging to see after which action Eclipse is freezing.

**Comment by swixfort** [comment]
The last steps are:
POST /sap/bc/adt/refactorings?step=execute
then
GET /sap/…/classname
After the GET nothings happening anymore.

**Comment by swixfort** [comment]
This seems to stick to this one machine. On another machine and on the ones from colleagues this error does not occur.
