### ISSUE TITLE
Marketplace Installation Failed

### ISSUE THREAD

**Issue by TimoStahl** [andau/abap-code-insight#6]
Hey,

I wanted to try out your plugin, unfortunately I can't install it.

`Cannot complete the install because one or more required items could not be found.
Software currently installed: ABAP Code Insight 0.3.0.1 (abap.code.insight.feature.feature.group 0.3.0.1)
Missing requirement: ABAP Code Insight 0.3.0.1 (abap.code.insight.plugin 0.3.0.1) requires 'osgi.bundle; org.eclipse.jdt.junit 3.11.0' but it could not be found
Cannot satisfy dependency:
From: ABAP Code Insight 0.3.0.1 (abap.code.insight.feature.feature.group 0.3.0.1)
To: org.eclipse.equinox.p2.iu; abap.code.insight.plugin [0.3.0.1,0.3.0.1]`

Eclipse IDE for JavaScript and Web Developers
Version: 2019-03 (4.11.0)
Build id: 20190314-1200

What Software/Plugin is missing in my Eclipse Installation? Do I have to use Eclipse for Java Developers?

**Comment by TimoStahl** [comment]
After installing this:

![image](https://user-images.githubusercontent.com/1961634/58095258-e9f4e480-7bd2-11e9-8110-308579d56474.png)


it seems to be working

**Comment by milloenchen** [comment]
Hello!
I have the same issue here and I only have the ADT installed in Eclipse, no Java/Web/OSGi.
Is there a possibility to install it without?

Version: 2020-12 (4.18)
Build id: I20201028-1800

Kind regards!
