### ISSUE TITLE
plugin not working in eclipse 2019-03?

### ISSUE THREAD

**Issue by trashdating** [andau/abap-code-insight#7]
I have installed the plugin on both my pc and laptop and followed the manual with the -clean startup but somehow it will not start to show the references above the methods for ABAP classes z classes and methods.

I am clueless how to get this plugin working now, I checked the preferences and everything seems fine. Is there a checklist or way I can check a correct functioning of this plugin or what is wrong?

Kind regards
Arthur
![Clipboard03](https://user-images.githubusercontent.com/34244207/59509828-703ed680-8eb2-11e9-9823-eec0abcef536.jpg)

**Comment by andau** [comment]
What Eclipse version are you using?

**Comment by lucasborin** [comment]
Hi @andau,

Version: 2019-09 R (4.13.0)
Build id: 20190917-1200

... and it is not working here. Could you please check?

Regards,
Lucas
